"""Adds repositories/archives."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/reboot-dev/pyprotoc-plugin repository. If you
# encounter it anywhere else it is because it has been copied there in
# order to simplify adding transitive dependencies. If you want a
# different version of pyprotoc-plugin follow the Bazel build
# instructions at https://github.com/reboot-dev/pyprotoc-plugin.
########################################################################

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

def repos(external = True, repo_mapping = {}):
    """Adds repositories/archives needed by pyprotoc-plugin

    Args:
          external: whether or not we're invoking this function as though
            though we're an external dependency
          repo_mapping: passed through to all other functions that expect/use
            repo_mapping, e.g., 'git_repository'
    """
    maybe(
        http_archive,
        name = "rules_python",
        sha256 = "4f7e2aa1eb9aa722d96498f5ef514f426c1f55161c3c9ae628c857a7128ceb07",
        strip_prefix = "rules_python-1.0.0",
        url = "https://github.com/bazel-contrib/rules_python/releases/download/1.0.0/rules_python-1.0.0.tar.gz",
        repo_mapping = repo_mapping,
    )

    # Bazel 8's WORKSPACE suffix runs
    # `@rules_java//java:rules_java_deps.bzl%rules_java_dependencies`,
    # which only exists from `rules_java` 8.0.0 on, and `protobuf_deps()`
    # would otherwise claim the name for 7.12.2. 8.12.0 is the version
    # Bazel 8.7.0's own suffix declares; 8.16.1 does not work, as its
    # `rules_java_deps.bzl` `load()`s `@bazel_features`, which nothing
    # declares before the suffix runs.
    maybe(
        http_archive,
        name = "rules_java",
        sha256 = "1558508fc6c348d7f99477bd21681e5746936f15f0436b5f4233e30832a590f9",
        url = "https://github.com/bazelbuild/rules_java/releases/download/8.12.0/rules_java-8.12.0.tar.gz",
        repo_mapping = repo_mapping,
    )

    if "com_google_protobuf" not in native.existing_rules():
        git_repository(
            name = "com_google_protobuf",
            remote = "https://github.com/protocolbuffers/protobuf",
            # Release v3.19.4.
            # TODO(codingcanuck): Update to a newer release after
            # https://github.com/protocolbuffers/protobuf/issues/9688 is fixed.
            commit = "22d0e265de7d2b3d2e9a00d071313502e7d4cccf",
            shallow_since = "1643340956 -0800",
            repo_mapping = repo_mapping,
        )

    if external and "com_github_reboot_dev_pyprotoc_plugin" not in native.existing_rules():
        git_repository(
            name = "com_github_reboot_dev_pyprotoc_plugin",
            remote = "https://github.com/reboot-dev/pyprotoc-plugin",
            commit = "9f7a281670f03b77140c4437ac2a56b86f978af6",
            shallow_since = "1649038239 +0000",
            repo_mapping = repo_mapping,
        )
